name: 02-2 - Deploy

on:
  workflow_call

jobs:
  AzureDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Compose File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          port: ${{ secrets.AZURE_PORT }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

          source: "./docker-compose.yml"
          target: "."

      - name: Start App
        uses: appleboy/ssh-action@v01.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          port: ${{ secrets.AZURE_PORT }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

          script: |
            echo ${{ secrets.DEMODOCKER_PAT }} | docker login ghcr.io -u ${{github.actor}} --password-stdin

            docker compose pull ghcr.io/davidlaclef/demodocker-back:latest
            docker compose pull ghcr.io/davidlaclef/demodocker-front:latest

            docker compose up -d --remove-orphans